"use client";

import Link from "next/link";
import { Calendar, FileText, Plus, Stethoscope } from "lucide-react";

type CaseDetailClientProps = {
  caseId: string;
};

export function CaseDetailClient({ caseId }: CaseDetailClientProps) {
  return (
    <div className="space-y-6">
      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 shadow-2xl shadow-black/20">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
          <div>
            <p className="text-sm text-cyan-200">Patient case</p>
            <h2 className="mt-1 text-2xl font-semibold text-white">{caseId}</h2>
            <p className="mt-2 max-w-3xl text-sm text-slate-300">
              This page organizes clinician-entered context, neuro-data runs,
              longitudinal monitoring, and report access. Diagnoses shown here
              are clinical context entered by a clinician, not generated by Coherence.
            </p>
          </div>

          <Link
            href={`/upload?caseId=${caseId}`}
            className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-cyan-200"
          >
            <Plus className="h-4 w-4" />
            Start new run
          </Link>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <Stethoscope className="h-5 w-5 text-cyan-200" />
          <h3 className="mt-3 font-semibold text-white">Clinical context</h3>
          <p className="mt-2 text-sm text-slate-400">
            Established diagnoses, medications, therapies, and symptom scales are
            stored as clinician-entered context.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <Calendar className="h-5 w-5 text-violet-200" />
          <h3 className="mt-3 font-semibold text-white">Longitudinal tracking</h3>
          <p className="mt-2 text-sm text-slate-400">
            Future runs can compare structural, diffusion, and EEG-derived
            measurements across timepoints.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <FileText className="h-5 w-5 text-amber-200" />
          <h3 className="mt-3 font-semibold text-white">Reports</h3>
          <p className="mt-2 text-sm text-slate-400">
            Reports are supplementary, non-diagnostic summaries for clinician review.
          </p>
        </div>
      </div>

      <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
        <h3 className="font-semibold text-white">Runs</h3>
        <p className="mt-2 text-sm text-slate-400">
          Once a run is created, it will appear in this case record with pipeline
          status, uploaded files, evidence ledger entries, and report outputs.
        </p>

        <div className="mt-4 rounded-xl border border-dashed border-white/15 bg-black/20 p-6 text-center text-sm text-slate-400">
          No run list is wired here yet. Use the upload flow to create a run.
        </div>
      </div>
    </div>
  );
}

export default CaseDetailClient;