import { GENERAL_DISCLAIMER, reportInterpretationStatement } from "@/lib/clinical-copy";
import type { NeuroRun, PatientCase } from "@/lib/types";
import { EvidenceLedger } from "./evidence-ledger";

export function ReportPreview({ run, patientCase }: { run: NeuroRun; patientCase?: PatientCase | null }) {
  const evidence = run.outputs?.evidenceLedger ?? [];

  return (
    <article className="space-y-5">
      <section className="rounded-lg border border-line bg-panel/75 p-5">
        <h2 className="text-xl font-semibold text-white">Structured non-diagnostic report</h2>
        <p className="mt-3 text-sm leading-6 text-slate-300">{GENERAL_DISCLAIMER}</p>
      </section>
      <section className="grid gap-4 md:grid-cols-2">
        {[
          ["Administrative details", `Case: ${patientCase?.displayName ?? run.caseId}. Run: ${run.id}. Modality: ${run.modality.replace("_", " ")}.`],
          ["Data inputs", run.inputFiles.length ? `${run.inputFiles.length} registered file(s) available for review.` : "No input files are attached in this placeholder view."],
          ["Quality-control summary", "Quality-control flags will be shown when backend processing is complete."],
          ["Structural MRI findings placeholder", "Structural measurement summaries will appear here when available."],
          ["Diffusion findings placeholder", "Diffusion and connectome summaries will appear here when available."],
          ["EEG findings placeholder", "EEG trace, spectrogram, and band-power summaries will appear here when available."],
          ["Longitudinal comparison placeholder", "Comparison across timepoints will be presented as supplementary context, with uncertainty noted."],
          ["Limitations", "No diagnosis, prediction, confirmation, or rule-out statement is generated by Coherence."]
        ].map(([title, body]) => (
          <div key={title} className="rounded-lg border border-white/10 bg-white/[0.03] p-5">
            <h3 className="font-semibold text-white">{title}</h3>
            <p className="mt-2 text-sm leading-6 text-slate-300">{body}</p>
          </div>
        ))}
      </section>
      <EvidenceLedger items={evidence} />
      <section className="rounded-lg border border-cyan-300/25 bg-cyan-300/10 p-5">
        <h3 className="font-semibold text-cyan-50">Non-diagnostic interpretation statement</h3>
        <p className="mt-2 text-sm leading-6 text-cyan-50/85">{run.report?.interpretationStatement ?? reportInterpretationStatement}</p>
      </section>
    </article>
  );
}
